# For better debbuging experience:
    # Set repo variables:
    # ACTIONS_RUNNER_DEBUG=true
    # ACTIONS_STEP_DEBUG=true
    # TODO: evaluate setting this to the .env
name: SyncSystem - Multiplatform - Pipeline Debug

on:
    push:
        branches:
            - main

jobs:
    debug:
        runs-on: ubuntu-latest

        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
                tools: composer

            - name: Change to Repository Directory
              run: cd $GITHUB_WORKSPACE

            - name: Install Composer dependencies
              run: composer install
              working-directory: ''

            - name: Check Endpoints
            #working-directory: ./syncsystem-laravel8-v1
              run: |
                until $(curl -s -o /dev/null -w "%{http_code}" https://ftppipelinev1backendphplaravel8v1poc1.syncsystem.com.br/system/setup/ https://ftppipelinev1multiplatformphplaravel8v1poc1.syncsystem.com.br/system/setup/ == 200); do
                echo "Waiting for endpoints..."
                sleep 30
                done
              timeout-minutes: 5
              shell: bash
